# docker exec -ti django-itsm python manage.py migrate
# docker exec -ti django-itsm python manage.py createsuperuser
version: "3.2"

services:

  django-itsm:
    image: django-itsm:dev
    build:
      context: .
      dockerfile: dockerfile
    container_name : django-itsm
    hostname: django-itsm
    ports:
      - "8002:8000"
    volumes:
      - ./volumes/data:/data:rw
      - ./volumes/etc/itsm:/etc/itsm:ro
    restart: always
    networks:
      - default
      - mariadb


networks:
  mariadb:
    external: true
