INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Django Template
repo_url: https://gitlab.com/nofusscomputing/infrastructure/configuration-management/django_app
edit_uri: '/-/ide/project/nofusscomputing/infrastructure/configuration-management/django_app/edit/development/-/docs/'

plugins:
  mkdocstrings:
    enabled: true
    handlers:
      python:
        setup_commands:
          - import os
          - import django
          - os.chdir('app/')
          - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "app.settings")
          - django.setup()
        options:
          find_stubs_package: true
          heading_level: 2
          inherited_members: false
          members_order: source
          paths: [ '.' ]
          parameter_headings: false
          show_category_heading: true
          show_if_no_docstring: true
          show_labels: false
          show_object_full_path: false
          show_root_heading: false
          show_root_full_path: true
          show_root_toc_entry: false
          show_signature_annotations: false
          show_source: false
          show_submodules: true
          summary: true


nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Django Template:

    - projects/django-template/index.md

    - Administration:

      - projects/django-template/administration/index.md

    - Development:

      - projects/django-template/development/index.md

      - Application API:

        - projects/django-template/development/api/index.md

        - Models:

          - projects/django-template/development/api/models/index.md

          - projects/django-template/development/api/models/core_history_save.md

          - projects/django-template/development/api/models/itam_device.md

          - projects/django-template/development/api/models/access_organization_permission_checking.md

        - Unit Testing:

          - projects/django-template/development/api/tests/index.md

          - projects/django-template/development/api/tests/model_permissions.md

          - projects/django-template/development/api/tests/model_permissions_organization_manager.md

          - projects/django-template/development/api/tests/model_permission_add.md

          - projects/django-template/development/api/tests/model_permission_add_organization_manager.md

          - projects/django-template/development/api/tests/model_permission_change.md

          - projects/django-template/development/api/tests/model_permission_change_organization_manager.md

          - projects/django-template/development/api/tests/model_permission_delete.md

          - projects/django-template/development/api/tests/model_permission_delete_organization_manager.md

          - projects/django-template/development/api/tests/model_permission_view.md

          - projects/django-template/development/api/tests/model_permission_view_organization_manager.md

          - projects/django-template/development/api/tests/model_permissions_api.md

          - projects/django-template/development/api/tests/model_permission_api_add.md

          - projects/django-template/development/api/tests/model_permission_api_change.md

          - projects/django-template/development/api/tests/model_permission_api_delete.md

          - projects/django-template/development/api/tests/model_permission_api_view.md

          - projects/django-template/development/api/tests/model_history.md

          - projects/django-template/development/api/tests/model_history_child_item.md

          - projects/django-template/development/api/tests/model_history_parent_item.md

          - projects/django-template/development/api/tests/model_history_permissions.md

    - User:

      - projects/django-template/user/index.md

      - Access:

        - projects/django-template/user/access/index.md

        - projects/django-template/user/access/organization.md

      - projects/django-template/user/configuration.md

      - projects/django-template/user/api.md

      - projects/django-template/user/config_management/index.md

      - Core:

        - projects/django-template/user/core/index.md

      - ITAM:

        - projects/django-template/user/itam/index.md

        - projects/django-template/user/itam/device.md

        - projects/django-template/user/itam/operating_system.md

        - projects/django-template/user/itam/software.md

      - projects/django-template/user/settings.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

